#ifndef __DHT22_H__
#define __DHT22_H__

typedef unsigned char uchar;
typedef unsigned int  uint;

unsigned char DHT22_num = 0;


uchar ucharFLAG,uchartemp;
uchar shidu_shi,shidu_ge,wendu_shi,wendu_ge,wendu_dian,shidu_dian;
uchar ucharT_data_H,ucharT_data_L,ucharRH_data_H,ucharRH_data_L,ucharcheckdata;
uchar ucharT_data_H_temp,ucharT_data_L_temp,ucharRH_data_H_temp,ucharRH_data_L_temp,ucharcheckdata_temp;
uchar ucharcomdata;
uchar ErrFLAG;

#endif